site_name: My Docs

theme:
    name: cinder

docs_dir: "mkdocs"
site_dir: "nublado/appdocs/static/mkdocs_build"

nav:
- Home: "index.md"
- User Guide:
    - "Sources": "sources.md"
    - "Contexts": "contexts.md"
- About:
    - "About Me": "about-me.md"
    - "Release Notes": "release-notes.md"
