# Generated by Django 2.1.3 on 2018-11-27 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'validation_email_unique'}, max_length=50, unique=True, validators=[django.core.validators.EmailValidator(code='email', message='validation_email_format')], verbose_name='label_email'),
        ),
    ]
