# Generated by Django 3.0.2 on 2020-02-01 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='characters', message='validation_user_name_characters', regex='^([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ.]+ ?)+$')], verbose_name='label_first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='characters', message='validation_user_name_characters', regex='^([a-zA-ZáéíóúüñÁÉÍÓÚÜÑ.]+ ?)+$')], verbose_name='label_last_name'),
        ),
    ]
