# Generated by Django 3.0.2 on 2020-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabsource',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'label_source_book'), (2, 'label_source_website'), (3, 'label_source_blog'), (4, 'label_source_created'), (5, 'label_source_other')], default=4, verbose_name='label_vocab_source_type'),
        ),
    ]
